### PR TITLE
[SPARK-16654][CORE][WIP] Add UI coverage for Application Level Blacklisting

### PR DESCRIPTION
**Pull request by jsoltren**
## What changes were proposed in this pull request?

Builds on top of work in SPARK-8425 to update Application Level
Blacklisting in the scheduler.

Adds a UI to these patches by:
- defining new listener events for blacklisting and unblacklisting,
  nodes and executors;
- sending said events at the relevant points in BlacklistTracker;
- adding JSON (de)serialization code for these events;
- augmenting the Executors UI page to show which, and how many,
  executors are blacklisted;
- adding a unit test to make sure events are being fired;
- adding HistoryServerSuite coverage to verify that the SHS reads
  these events correctly.

## How was this patch tested?

./dev/run-tests
testOnly org.apache.spark.util.JsonProtocolSuite
testOnly org.apache.spark.scheduler.BlacklistTrackerSuite
testOnly org.apache.spark.deploy.history.HistoryServerSuite

blacklist

### CODE REVIEW

**Comment by ajbozarth** [comment]
Found this via the dev list. I haven't had a detailed look at your code, but I do have some comments on the UI portion. I mention this in the JIRA, but I think adding another column to the table with just a Yes/No value is overkill. I think including a (Blacklisted) in the Status column would be cleaner. I do like the summary column though.

**Comment by squito** [comment]
thanks for the comments @ajbozarth , I agree the "status" column does seem like a good place for it, sorry for overlooking the comments in the jira.  (Also this is exactly the type of comment we're looking for -- I can review the code but don't have much of an opinion on the look of the UI).

**Comment by jsoltren** [comment]
Thanks @ajbozarth and @squito ! I've posted a new patch set with this UI feedback.

**Comment by ajbozarth** [comment]
I like the UI update

**Comment by ajbozarth** [comment]
was going through open prs I've commented on and noticed this was still open even though the spark pr was merged

**Pull request closed without merging**
